### PR TITLE
can you check out our arrow changes ?

### PR DESCRIPTION
**Pull request by JosePedroDias**
This allows for different nodes to have different radiuses with arrows getting displayed properly.
I believe I have a bug somewhere because the arrow directions got swapped sometimes though.

### CODE REVIEW

**Comment by maurizzzio** [comment]
thanks for the PR, have you pulled the latest version of greuler? I think I solved this issue a few days ago

https://jsbin.com/fuwifesama/edit?html,js,output

**Comment by JosePedroDias** [comment]
I must check your code then. Anyway compare the 2 results:

yours:
http://output.jsbin.com/yelewo/latest/quiet

mine:
http://output.jsbin.com/yelewo/latest/quiet?mine

(oh and congrats, awesome project and good landing page too)

**Comment by JosePedroDias** [comment]
...would also be awesome to support rectangle nodes instead of only circles O:)

**Comment by maurizzzio** [comment]
Ok nice, this is what I understood from your code:

- for each path you're creating a new point right at the border of the circle so for a non-loop edge between u and v the path consisted before in: `[u, center, v]` and now it's made of `[a point right at the border of u which is collinear with u mid, mid, a point right at the border of v which is collinear with mid v]`
- also the distance between the edges was increased

I actually did something similar in https://github.com/maurizzzio/greuler/blob/master/src/elements/edge.js#L167-L168

- instead of creating the points at the edges of the circles I moved u to be right at the border, same with v

So technically we did the same xD, the only difference I see is the distance between the edges

**Comment by maurizzzio** [comment]
Perhaps the hardcoded number that controls the distance between edges should be configurable from the outside

**Comment by JosePedroDias** [comment]
OK, awesome. Ditching my PR. :) thanks

**Pull request closed without merging**
